controller_manager:
  ros__parameters:
    update_rate: 250
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      panda_joint1:
        trajectory: 0.2
        goal: 0.1
      panda_joint2:
        trajectory: 0.2
        goal: 0.1
      panda_joint3:
        trajectory: 0.2
        goal: 0.1
      panda_joint4:
        trajectory: 0.2
        goal: 0.1
      panda_joint5:
        trajectory: 0.2
        goal: 0.1
      panda_joint6:
        trajectory: 0.2
        goal: 0.1
      panda_joint7:
        trajectory: 0.2
        goal: 0.1
